### ISSUE TITLE
Enable Backup and Open Store installation for Pro5

### ISSUE THREAD

**Issue by DiogoConstantino** [MariusQuabeck/magic-device-tool#100]
I see no point on not allowing some of the features for Meizu Pro5, like backup and Open Store installation. They don't require having the device to test them, and I've just made successful tests for both.

May does features be enabled even if the others won't be enabled for now?

**Comment by MariusQuabeck** [comment]
I've added the Pro 5 with UBports Backup Commit https://github.com/MariusQuabeck/magic-device-tool/commit/1e87ddbfc83804fa6acda9e4f6dba63c9f42df7a
