### ISSUE TITLE
Backup over rsync in snap version not working (krillin)

### ISSUE THREAD

**Issue by Rom4nB** [MariusQuabeck/magic-device-tool#108]
What was done?
MDT snap version was installed. ADB on device (krillin) enabled. Backup was selected.

What went wrong?
When the backup wants to establish the ssh connection (creating ssh keys) there is already an error.

See here:
https://paste.ofcode.org/iXx673q4qYyRZwXCw3Eu8y

The backup cannot be started.

**Comment by MariusQuabeck** [comment]
known issue but as we are removing all ubuntu touch options from mdt very soon I'll close this
