### ISSUE TITLE
README.md procedure not working

### ISSUE THREAD

**Issue by Julientroploin** [MariusQuabeck/magic-device-tool#109]
Hello,

trying to backup my Bq Aquarius E4.5 UbuntuEdition, I followed steps in the README.md file but procedure aborted. But the procedure on https://ubports.com/page/get-ubuntu-touch page is working.

Is the README.md outdeted ? Was I making something wrong ? 

Output with README.md file procedure : 
```
BQ Aquaris E4.5 - krillin


Ubuntu: 

[1] Install Ubuntu
[2] Install OpenStore

[3]  Back Up your UBports device

[4] Screencast

[0] Back to menu 

Enter option: 3








./devices/generic/ubuntu/ubports-backup.sh: line 236: read_setting: command not found
./devices/generic/ubuntu/ubports-backup.sh: line 237: read_setting: command not found
./devices/generic/ubuntu/ubports-backup.sh: line 238: read_setting: command not found
./devices/generic/ubuntu/ubports-backup.sh: line 239: read_setting: command not found
./devices/generic/ubuntu/ubports-backup.sh: line 240: read_setting: command not found
./devices/generic/ubuntu/ubports-backup.sh: line 241: [: : integer expression expected
./devices/generic/ubuntu/ubports-backup.sh: line 246: read_setting: command not found

UBports (tiny) Backup

This module will make a simple backup or restore of the user data in your UBports device. It is currently in alpha stage and no liability is taken for lost data.
NOTE: Currently it is not possible to make a backup of installed Apps, we hope to provide this on a later stage...

The things You will need:

For backup to SD cards:
*) An SD card inserted in your phone

OR

For backup to remote PCs or servers:
*) the DNS name or IP address of a backup server that can be used with scp/rsync
*) your username on this server
*) (optional) a path to the remote directory, which will be used to store the backup: $HOME/<optional_folder>/ubports_backup/<device_id> - enable advanced mode for this to work.

The script will create its own SSH key pair which will be then also pushed to the device. Currently we only support one username and one backup server!

Currently the following settings are configured:

Backup/Restore to/from ssh server
Backup server: 
Username: 
Server status: 
Device currently connected: JU002811
./devices/generic/ubuntu/ubports-backup.sh: line 285: [: : integer expression expected
Current backup path: @:$HOME/ubports_backup/JU002811


[1] Switch backup target

[2] Change backup server

[3] Change username

[4] Backup device JU002811

[5] Restore device JU002811

./devices/generic/ubuntu/ubports-backup.sh: line 311: [: : integer expression expected
[9] Switch to advanced mode

[0] Back to main MDT menu

Enter option:
```

The procedure on https://ubports.com/page/get-ubuntu-touch page : 

> git clone https://github.com/MariusQuabeck/magic-device-tool.git
> cd magic-device-tool
> sudo ./launcher.sh

**Comment by mike2github** [comment]
by me it was exactly the same...


_**./devices/generic/ubuntu/ubports-backup.sh: line 236: read_setting: command not found**_

 and surprise ... the solution by me was real rocket-sience...

i used a 1 $ USB-cable from china. I love china! Only the USB-Lights on the USB-Cable suck to much power...so the mobile-phone-device was not found by the PC and the heroic magic-device-tool.
so i unplugged the shiny-led-usb-cable...replaced it with a not so shiny black one...and the magic device tool found his phone.

**Comment by Julientroploin** [comment]
Don't think it is a problem with the cable : it is the default cable of the phone...
But your comment gave me an idea : I used the front USB-port of my PC, not one of the motherboard port. I've to try it !

By now, I'm not able to do it : I forgot my phone at work this WE.

Thank you for your comment, i'll try as soon as possible.

**Comment by MariusQuabeck** [comment]
we are removing all ubuntu touch otions from mdt very soon so I'll close this

**Comment by Julientroploin** [comment]
Thanks for this comment : it push me to come back on my problem before you remove options...
I made my backup via ssh https://askubuntu.com/questions/348714/how-can-i-access-my-ubuntu-phone-over-ssh#599041 and installed UBports following https://ubports.com/page/get-ubuntu-touch

Why are you removing ubuntu touch options ? I don't think all UT users installed UBport yet...
