### ISSUE TITLE
failed to flash fp2

### ISSUE THREAD

**Issue by pixelr0** [MariusQuabeck/magic-device-tool#111]
i am using the snap installed:   1.0 (293) 63MB devmode (with sudo) on ubuntu 16.04
Fairphone 2 flash legacy channel
everything went well until recovery mode, where i got this error

Please boot your Fairphone 2 into recovery mode by pressing Power & Volume Up (+)

Wait until you see the 'UBports Recovery' screen.
this can take up to ~30 seconds
Is your Fairphone 2 in recovery mode now? [Y] Y

Detecting device

faabf699	recovery
Device detected !
mount: mounting /dev/block/mmcblk1p1 on /sdcard failed: No such file or directory
sudo: ubuntu-device-flash: command not found

Move to your device to finish the setup.

You will see the Fairphone bootscreen for a few minutes now. Don't worry.

Cleaning up..
chown: cannot access '/root/snap/magic-device-tool/293/.cache/ubuntuimages/': No such file or directory

now the phone doesn't boot and apparently i can't turn it off o_O

**Comment by MariusQuabeck** [comment]
Hey  you can't use the snap for fp2. Please clone the repo and run the launcher.sh with sudo on Ubuntu 16.04 or newer. Please note that we will stop supporting Ubuntu Touch in MDT soonish so please check out the UBports installer.

**Comment by pixelr0** [comment]
yep, the launcher worked great. i checked the ubuntu installer but i like mdt better :D X-)
