### ISSUE TITLE
Update Nexus 4 and 7 (2013) to use UBPorts OTA-2

### ISSUE THREAD

**Issue by bgiesing** [MariusQuabeck/magic-device-tool#112]
https://ubports.com/blog/latest-news-1/post/ubuntu-touch-ota-2-release-78

UBports now officially supports the Nexus 4 and Nexus 7 (2013) so this should be updated to point to UBPort's servers instead of Canonical's.

**Comment by MariusQuabeck** [comment]
We will stop supporting Ubuntu Touch in MDT soon so we are not fixing anything there anymore. Please check out the UBports installer

**Comment by bgiesing** [comment]
There install doesn't work, just hangs on Flashing recovery on the Nexus 7 2013 so I guess I'll have to bring that up with them since this one worked.
