### ISSUE TITLE
need to have rooted devices ? 

### ISSUE THREAD

**Issue by Saaslys** [MariusQuabeck/magic-device-tool#113]
I try to install ubuntu
but after some write and erase it stop with this failed and stay in last rom

2017/10/30 18:56:53 Device is |hammerhead|
2017/10/30 18:56:53 Flashing version 42 from ubports-touch/legacy channel and server http://system-image.ubports.com to device hammerhead
2017/10/30 18:56:53 mkdir /root/snap: permission denied

Move to your device to finish the setup.

Cleaning up..

Exiting magic-device-tool. Bye Bye

**Comment by MariusQuabeck** [comment]
We will stop supporting Ubuntu Touch in MDT soon so we are not fixing anything there anymore. Please check out the UBports installer
