### ISSUE TITLE
try install maru without gApps

### ISSUE THREAD

**Issue by Saaslys** [MariusQuabeck/magic-device-tool#114]
hello 
i use nexus5 and try to install maruOs without gapps choice 2
when first reboot in twrp the device was loose 

Rebooting device..

This will take ~35 seconds. Don't disconnect your device!

rebooting into bootloader...
OKAY [  0.000s]
finished. total time: 0.050s
downloading 'boot.img'...
OKAY [  0.567s]
booting...
OKAY [  0.117s]
finished. total time: 0.683s
error: device not found

If i install with gapps it is working great, with one swipe to unlock. Maybe not unlock and reboot device ? 

regards

**Comment by MariusQuabeck** [comment]
> when first reboot in twrp the device was loose

don't disconnect the device while mdt is doing its magic ;)
I've just installed Maru without GApps via mdt without any problems.

**Comment by Saaslys** [comment]
hello 
in the process when switching to twrp the devices not going on twrp 
i 'am going to retry once more. 
regards
