### ISSUE TITLE
Fails to install dependencies on recent Ubuntu 17.10

### ISSUE THREAD

**Issue by jonnius** [MariusQuabeck/magic-device-tool#115]
On a recent Ubuntu 17.10 it won't success installing Ubuntu on my Phone (Fairphone 2), except I used the following workarround:

- install **phablet-tools** manually from older Ubuntu version (I used the zesty version).
- change PPA ubuntu-sdk-team/ppa to xenial, so that **ubuntu-device-flash** can be installed.

**Comment by MariusQuabeck** [comment]
Hey thanks for reporting this. Please note that we are dropping support for Ubuntu Touch very soon and we no longer recommend the script version. Please use the snap. For this specific problem please get in touch with @UBports and ask for the UBports installer.

**Comment by jonnius** [comment]
Alright then, thanks for your answer.
