### ISSUE TITLE
Backup fails due to SD card name mutation

### ISSUE THREAD

**Issue by PeterNerlich** [MariusQuabeck/magic-device-tool#116]
The system by canonical mounted the SD card to `/media/phablet/MICROSD 16G`, but the used code to detect this pipes it to `tr -d '[:space:]'`, eliminating the space and making the script fail:

    Now doing backup to SD card MICROSD16G...
    mkdir: cannot create directory ‘/media/phablet/MICROSD16G’: Permission denied
    rsync: mkdir "/media/phablet/MICROSD16G/./ubports_backup/JW053276" failed: No such file or directory (2)
    rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]
    
    Backup NOT OK!
    Press a key to continue...

https://github.com/MariusQuabeck/magic-device-tool/blob/70664ee2bc677ce99028faadb9f8fad96c13d319/devices/generic/ubuntu/ubports-backup.sh#L111

(using a BQ Aquaris E4.5)

**Comment by PeterNerlich** [comment]
after playing around with it for a bit it seems that the problem is that atm the pipe is needed to strip away spaces at the end, while a path name containing a space doesn't work anyway and get's interpreted as multiple paths, effectively making the script try both (or something), since it complains it cannot create the directory at first and then copies to the home directory and the second path.

**Comment by PeterNerlich** [comment]
creating a symlink on the phone manually doesn't work either

**Comment by Flohack74** [comment]
@PeterNerlich can you please test this for me, I am on business trip without SD card (and also I don't have a space so far in my phones :)) - The fix is in my repo https://github.com/Flohack74/magic-device-tool/tree/flo => checkout this branch and just test this function, could you do this? Thx!

**Comment by PeterNerlich** [comment]
I can confirm this works with my device. I'll mark this as closed. Thank you very much!
