### ISSUE TITLE
Repositories/packages mdt depends on are not available on Ubuntu 17.10

### ISSUE THREAD

**Issue by kwah-gh** [MariusQuabeck/magic-device-tool#118]
At least the following packages can not be installed:
* phablet-tools
* ubuntu-device-flash

Log:
  → phablet-tools: not found, installing...
Adding necessary apt repository: ppa:ubuntu-sdk-team/ppa
... snip ...
E: The repository 'http://ppa.launchpad.net/phablet-team/tools/ubuntu artful Release' does not have a Release file.
E: Package 'phablet-tools' has no installation candidate
  → ubuntu-device-flash: not found, installing...
... snip ...
E: Unable to locate package ubuntu-device-flash

**Comment by MariusQuabeck** [comment]
we are removing all ubuntu touch options from mdt very soon so I'll close this
