### ISSUE TITLE
Trying to install ubuntu touch to BQ M10 FHD

### ISSUE THREAD

**Issue by dlalleme** [MariusQuabeck/magic-device-tool#119]
Hello,

I just buy a BQ M10 FHD with android 6.0

the device is in developper mode, usb unlocked and OEM unlock
I try to install a UT image and it is impossible ..

Method Install using MDT

```
Flashing legacy channel

Creating filesystem with parameters:
Size: 444596224
Block size: 4096
Blocks per group: 32768
Inodes per group: 6784
Inode size: 256
Journal blocks: 1696
Label:
Blocks: 108544
Block groups: 4
Reserved block group size: 31
Created filesystem with 11/27136 inodes and 3502/108544 blocks
target reported max download size of 134217728 bytes
erasing 'cache'...
FAILED (remote: format for partition 'cache' is not allowed
)
finished. total time: 0.004s
Creating filesystem with parameters:
Size: 838860800
Block size: 4096
Blocks per group: 32768
Inodes per group: 7328
Inode size: 256
Journal blocks: 3200
Label:
Blocks: 204800
Block groups: 7
Reserved block group size: 55
Created filesystem with 11/51296 inodes and 6651/204800 blocks
target reported max download size of 134217728 bytes
erasing 'userdata'...
FAILED (remote: format for partition 'userdata' is not allowed
)
finished. total time: 0.004s
Creating filesystem with parameters:
Size: 1610612736
Block size: 4096
Blocks per group: 32768
Inodes per group: 8192
Inode size: 256
Journal blocks: 6144
Label:
Blocks: 393216
Block groups: 12
Reserved block group size: 95
Created filesystem with 11/98304 inodes and 12897/393216 blocks
target reported max download size of 134217728 bytes
erasing 'system'...
FAILED (remote: format for partition 'system' is not allowed
)
finished. total time: 0.004s
erasing 'recovery'...
FAILED (remote: format for partition 'recovery' is not allowed
)
finished. total time: 0.004s
rebooting into bootloader...
OKAY [ 0.003s]
finished. total time: 0.103s
Please wait
rm: impossible de supprimer '/home/xxxxxx/.cache/magic-device-tool/recovery-frieza.img': Aucun fichier ou dossier
```
The system begins the download for the img file 

```
2017/11/21 17:00:12 Device is |frieza|
2017/11/21 17:00:12 Flashing version 12 from ubports-touch/legacy channel and server http://system-image.ubports.com to device frieza
```
Then le system is blocked and the device is switch off.
If I switch on the device I have
```
can't flash recovery image

Wait until it reboots on its own!
Do not reboot manually!

Cleaning up..

```

When I launch the `adb reboot bootloader` command, the device switches off.

I tried the Install using system-image server install and I have the same problem 

Regards

**Comment by ILoveHubGit** [comment]
Hi
I've a similar problem. If I run sudo magic-device-tool (without sudo it does not work) I get the following output after I confirmed the FASTBOOT mode:
***************************************************************************************************************
Detecting device

ML002173	fastboot
Device detected !
'rxvt-unicode-256color': unknown terminal type.

Flashing legacy channel

Creating filesystem with parameters:
    Size: 1073741824
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8192
    Inode size: 256
    Journal blocks: 4096
    Label: 
    Blocks: 262144
    Block groups: 8
    Reserved block group size: 63
Created filesystem with 11/65536 inodes and 8536/262144 blocks
target reported max download size of 134217728 bytes
erasing 'cache'...
FAILED (remote: unknown command)
finished. total time: 0.002s
Creating filesystem with parameters:
    Size: 838860800
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 7328
    Inode size: 256
    Journal blocks: 3200
    Label: 
    Blocks: 204800
    Block groups: 7
    Reserved block group size: 55
Created filesystem with 11/51296 inodes and 6651/204800 blocks
target reported max download size of 134217728 bytes
erasing 'userdata'...
FAILED (remote: unknown command)
finished. total time: 0.002s
Creating filesystem with parameters:
    Size: 4194304000
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8000
    Inode size: 256
    Journal blocks: 16000
    Label: 
    Blocks: 1024000
    Block groups: 32
    Reserved block group size: 255
Created filesystem with 11/256000 inodes and 34123/1024000 blocks
target reported max download size of 134217728 bytes
erasing 'system'...
FAILED (remote: unknown command)
finished. total time: 0.002s
erasing 'recovery'...
FAILED (remote: unknown command)
finished. total time: 0.002s
rebooting into bootloader...
OKAY [  0.003s]
finished. total time: 0.053s
Please wait
rm: cannot remove '/root/snap/magic-device-tool/299/.cache/magic-device-tool/recovery-frieza.img': No such file or directory
recovery-frieza.img       100%[=====================================>]  11.18M  8.44MB/s    in 1.3s    
'rxvt-unicode-256color': unknown terminal type.

2017/12/16 16:12:04 Device is |frieza|
2017/12/16 16:12:04 Flashing version 12 from ubports-touch/legacy channel and server http://system-image.ubports.com to device frieza
2017/12/16 16:12:04 mkdir /root/snap/magic-device-tool/299/.cache/ubuntuimages: permission denied

Wait until it reboots on its own!
Do not reboot manually!

Cleaning up..

Exiting magic-device-tool. Bye Bye
***************************************************************************************************************
The magic-device-tool stops and my tablet stays in FASTBOOT Mode forever :-)
If I restart my tablet manually nothing has happened.
I did a factory reset before using the magic-device-tool. But this didn't make any difference.
Can someone help me?

**Comment by MariusQuabeck** [comment]
Hi please don’t use the script, use the snap 

Von meinem iPhone gesendet

**Comment by ILoveHubGit** [comment]
Hi Marius,

I used the snap :-(

**Comment by dlalleme** [comment]
Hello,
I'm waiting a new tablet cause BQ exchange the old one.
They send me a procedure to install ubuntu touch. I think the procedure is personnel with a serial number.
Call the BQ support and it will help you.
I hope the tablet will come soon !
Regards

**Comment by ILoveHubGit** [comment]
Hello,
Thanks for the advice. But my tablet is still working (running Ubuntu Touch) so no need to call BQ.
What I want is to replace Ubuntu Touch with the version of UB ports, so I get security updates again.
Regards

**Comment by MariusQuabeck** [comment]
we are removing all Ubuntu options from mdt very soon so I'll close this
