### ISSUE TITLE
Screencast feature is using the ssh key from root

### ISSUE THREAD

**Issue by Cypresslin** [MariusQuabeck/magic-device-tool#122]
Steps:
1. Connect a M10 tablet in developer mode, accept the access on the tablet.
2. Run `sudo ./launcher.sh`, select M10 HD -> screen cast
3. It will fail with "Permission Denied(Publickey)" error

Solution:
* Create a ssh key pair with root, and copy the public key to authorized_keys file on the tablet.

I think it's better to use the ssh private key from the current user, since it is the only public key that will get copied to the target.

**Comment by MariusQuabeck** [comment]
thats a know issue. just run it like 3-4 times and then it will work. this is not a bug in mdt, its a phablet-shell issue
