### ISSUE TITLE
wget: syntax flag '--show-progress' not portable know

### ISSUE THREAD

**Issue by gurucubano** [MariusQuabeck/magic-device-tool#125]
I used the MDT on an older Ubuntu system:

`uname -a`
`Linux linchen-ubuntu 3.13.0-92-generic #139-Ubuntu SMP Tue Jun 28 20:42:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

to flash UBports into my E4.5. The flag `--show-progress` is not known in wget version 1.15.
Either it should be omitted in any case, or only used if the flag is supported in the concrete version of wget, i.e. the syntax should be configured.

**Comment by MariusQuabeck** [comment]
Hey,

please don't run it as a script. Use the snap it has everything needed including the latest wget.
`snap install magic-device-tool --devmode`
Also we are dropping support for Ubuntu Phone really soon so you might want to take a look at the UBports Installer.
