### ISSUE TITLE
flashing ubuntu rc-proposed fail on bq aquaris fhd (frieza)

### ISSUE THREAD

**Issue by alebarra** [MariusQuabeck/magic-device-tool#14]
when i'm tryng to install ubuntu on aquaris fhd, script fail flashing image with a generic error:

2016/08/24 16:08:19 Device is |frieza|
2016/08/24 16:08:19 Flashing version 173 from ubuntu-touch/rc-proposed/bq-aquaris-pd.en channel and server https://system-image.ubuntu.com to device frieza
176.00 KB / 451.35 MB [________________] 0.04 % 219.82 KB/s 35m1scan't flash recovery image

Move to your device to finish the setup.

Cleaning up..

Exiting script. Bye Bye

**Comment by MariusQuabeck** [comment]
@alebarra 
Interesting it worked for me a few hours ago.
Is your M10 currently running android?
That would explain why the tool cant flash the recovery image because the bootloader is locked on android
