### ISSUE TITLE
Error,  install in 'Meizu MX 4 - arale' - 'Screencast'

### ISSUE THREAD

**Issue by jesusgascon** [MariusQuabeck/magic-device-tool#17]
Error, when I try to install in 'Meizu MX 4 - arale' - 'Screencast':

Detecting device
xxxxxxxx	device

Device detected !
Host [localhost]:2222 not found in /home/jesus/.ssh/known_hosts
ls: no se puede acceder a '/home/jesus/.ssh/*.pub': No existe el archivo o el directorio
Pseudo-terminal will not be allocated because stdin is not a terminal.
Warning: Permanently added '[localhost]:2222' (RSA) to the list of known hosts.
Permission denied (publickey).

Host [localhost]:2222 not found in /home/jesus/.ssh/known_hosts
ls: no se puede acceder a '/home/jesus/.ssh/*.pub': No existe el archivo o el directorio

**Comment by MariusQuabeck** [comment]
Hey please run
sudo apt install openssh-server
ssh-keygen
(just press enter a few times)
and try the tool again.

**Comment by jesusgascon** [comment]
That's true. I'd formatted computer and didn't install ash-server.  

Thanks
