### ISSUE TITLE
Samsung Nexus 10 - Ubuntu Touch Installation Not Working

### ISSUE THREAD

**Issue by brickquinn** [MariusQuabeck/magic-device-tool#20]
Flash Appears to work fine, but after it reboots I get a Picture of a micro chip with a red line through it.  Saying need to bring it to a service center.  Any ideas are welcome?   Note: I got the same  when I attempted to install from UBPorts directly.  So I presume it is a bad build, but did you ever get it to work before on a Nexus 10?

The output of the script looks like:
```
Detecting device

R32D1045W1E	fastboot
Device detected !




















Flashing stable channel

Creating filesystem with parameters:
    Size: 553648128
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 6768
    Inode size: 256
    Journal blocks: 2112
    Label: 
    Blocks: 135168
    Block groups: 5
    Reserved block group size: 39
Created filesystem with 11/33840 inodes and 4363/135168 blocks
erasing 'cache'...
OKAY [  0.042s]
sending 'cache' (10372 KB)...
OKAY [  1.670s]
writing 'cache'...
OKAY [  0.316s]
finished. total time: 2.028s
Creating filesystem with parameters:
    Size: 14273216512
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8144
    Inode size: 256
    Journal blocks: 32768
    Label: 
    Blocks: 3484672
    Block groups: 107
    Reserved block group size: 855
Created filesystem with 11/871408 inodes and 96018/3484672 blocks
erasing 'userdata'...
OKAY [  0.227s]
sending 'userdata' (137478 KB)...
OKAY [ 22.122s]
writing 'userdata'...
OKAY [  3.976s]
finished. total time: 26.325s
rebooting into bootloader...
OKAY [  0.001s]
finished. total time: 0.452s

2016/10/01 12:46:29 Device is |manta|
2016/10/01 12:46:29 Flashing version 7 from ubuntu-touch/stable channel and server http://system-image.ubports.com to device manta
2016/10/01 12:47:26 Start pushing /home/admin-local/.cache/ubuntuimages/pool/manta-92629bb09feb236b3ba5d918ccd028ed0d28675f40dc7bd662870a9b0067112b.tar.xz to device
2016/10/01 12:47:26 Start pushing /home/admin-local/.cache/ubuntuimages/pool/keyring-f812366ff5018823acd3918f65837f7ade9679431e6e5ca6627a4e48f8dd643b.tar.xz to device
2016/10/01 12:47:26 Start pushing /home/admin-local/.cache/ubuntuimages/ubuntu-touch/stable/manta/version-7.tar.xz to device
2016/10/01 12:47:26 Start pushing /home/admin-local/.cache/ubuntuimages/gpg/image-master.tar.xz to device
2016/10/01 12:47:26 Start pushing /home/admin-local/.cache/ubuntuimages/gpg/image-signing.tar.xz to device
2016/10/01 12:47:26 Start pushing /home/admin-local/.cache/ubuntuimages/pool/ubuntu-0e424a43b6c77f08dfc8a8d7f0f6fa076594cafdcf66323c1f82f3faa6f3f838.tar.xz to device
2016/10/01 12:47:27 Done pushing /home/admin-local/.cache/ubuntuimages/pool/keyring-f812366ff5018823acd3918f65837f7ade9679431e6e5ca6627a4e48f8dd643b.tar.xz to device
2016/10/01 12:47:27 Done pushing /home/admin-local/.cache/ubuntuimages/ubuntu-touch/stable/manta/version-7.tar.xz to device
2016/10/01 12:47:27 Done pushing /home/admin-local/.cache/ubuntuimages/gpg/image-master.tar.xz to device
2016/10/01 12:47:27 Done pushing /home/admin-local/.cache/ubuntuimages/gpg/image-signing.tar.xz to device
2016/10/01 12:47:33 Done pushing /home/admin-local/.cache/ubuntuimages/pool/manta-92629bb09feb236b3ba5d918ccd028ed0d28675f40dc7bd662870a9b0067112b.tar.xz to device
2016/10/01 12:48:09 Done pushing /home/admin-local/.cache/ubuntuimages/pool/ubuntu-0e424a43b6c77f08dfc8a8d7f0f6fa076594cafdcf66323c1f82f3faa6f3f838.tar.xz to device
2016/10/01 12:48:09 Created ubuntu_command: /home/admin-local/.cache/ubuntuimages/ubuntu_commands303540411
2016/10/01 12:48:09 Rebooting into recovery to flash

Move to your device to finish the setup.

Cleaning up..

Exiting script. Bye Bye
```

**Comment by MariusQuabeck** [comment]
Hey thanks for reporting this issue,

I reached out to the UBports guys, it seems like that the Nexus 10 port gets no longer maintained.
I don't have a Nexus 10 atm so I can't debug that.

As soon as something changes about that, I will reach out to you

**Comment by brickquinn** [comment]
BTW Cyanogenmod doesnt not work either.

Installing TWRP recovery

sending 'recovery' (9296 KB)...
OKAY [  1.547s]
writing 'recovery'...
OKAY [  0.238s]
finished. total time: 1.784s

Rebooting device..

This will take ~35 seconds. Don't disconnect your device!

rebooting into bootloader...
OKAY [  0.001s]
finished. total time: 0.452s
< waiting for device >
downloading 'boot.img'...
OKAY [  1.726s]
booting...
OKAY [  0.470s]
finished. total time: 2.196s



Pushing zip's to device

Please wait this can take a while

You may see a prompt asking you for read/write permissions
Ignore that prompt, the tool will take care of the installation

  → CM 13 zip 
error: device not found

  → gapps zip
error: device not found

=========================================

Installing Cyanogenmod..

Unable to locate zip file '/sdcard/manta-snapshot.zip'.
Installing zip file '/sdcard/manta-snapshot.zip'
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
Failed to map file '/sdcard/manta-snapshot.zip'
Error installing zip file '/sdcard/manta-snapshot.zip'
Done processing script file

Installing GApps..

Unable to locate zip file '/sdcard/open_gapps-arm-6.0-nano-20160811.zip'.
Installing zip file '/sdcard/open_gapps-arm-6.0-nano-20160811.zip'
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
Failed to map file '/sdcard/open_gapps-arm-6.0-nano-20160811.zip'
Error installing zip file '/sdcard/open_gapps-arm-6.0-nano-20160811.zip'
Done processing script file

Wipe cache..

Formatting Cache using make_ext4fs...
Done processing script file
Wiping Dalvik Cache Directories...
-- Dalvik Cache Directories Wipe Complete!
Done processing script file

The device is now rebooting. Give it time to flash the new ROM. It will boot on its own.


Cleaning up..

Exiting script. Bye Bye

**Comment by MariusQuabeck** [comment]
I've ordered a N10, fix is coming soon

**Comment by MariusQuabeck** [comment]
Hey I had to remove the Ubuntu options because no channel worked for the n10 but I fixed all the Android options. Please try again.

**Comment by unixsamurai** [comment]
Any update to this? I can install Lineage OS 13, via the MDT (works like a champ), but Ubuntu pretends to install, then boots into to Picture of a micro chip with a red line through it. 

Trying to install from an Ubuntu 17.04 PC to the Nexus 10.

**Comment by MariusQuabeck** [comment]
@unixsamurai this is not a bug in mdt. the UBports Ubuntu port for the Nexus 10 is broken and afaik was never working. Please report this at UBports

**Comment by unixsamurai** [comment]
Ok thanks. MDT is awesome for LineageOS!
