### ISSUE TITLE
BQ Aquaris E4.5 (krillin) - Options to install Android not presented

### ISSUE THREAD

**Issue by siladi** [MariusQuabeck/magic-device-tool#21]
Are there any plans to implement this feature for this  particular phone model? Thanks.

**Comment by MariusQuabeck** [comment]
Yes I'm planning to add this feature as soon as I've found a cyanogenmod version that works (there is a cm port on htcmania but the capacitive buttons don't work there on the Ubuntu edition devices). The stock android images from BQ can only be flashed using the sp flash tool.

**Comment by siladi** [comment]
OK. True, the capacitive buttons fail to light up, but they do function.

**Comment by MariusQuabeck** [comment]
I'm aware of that but they do not only not light up (which is expected because that's the hardware difference on the ubuntu editions) they actually do not work with the cyanogenmod port from htcmania. They work fine with the stock android from BQ
