### ISSUE TITLE
Provide information for Fedora

### ISSUE THREAD

**Issue by amilopowers** [MariusQuabeck/magic-device-tool#26]
Hi
First thank you for your great work!

I am trying to use your tool on Fedora 24 for my Nexus 5.
Could you please provide information on what packages we need to have installed in order to run you script? It asks to install "phablet-tools" and others but the Fedora repos don't have those packages.

I would appreciate also information from which PPA we could get those packages on not Debian based systems.

With my best regards
amilopowers

**Comment by MariusQuabeck** [comment]
Hi,

the thing is that we are using ubuntu specific tools and PPA's in the tool.
I will look into it how to get it running on Fedora and then I'll get back to you!

Best regards
Marius

**Comment by amilopowers** [comment]
Hello
Is there any progress?
Don't want to bother you....

**Comment by kristbaum** [comment]
If you are on Fedora, have you tried using the snap?

**Comment by MariusQuabeck** [comment]
@amilopowers Yes if you are on Fedora please use the snap.
