### ISSUE TITLE
Install in Meizu MX4 (Android Version)?

### ISSUE THREAD

**Issue by jesusgascon** [MariusQuabeck/magic-device-tool#28]
good mornng,

i've got a Meizu MX4 (android version) and i would like to know if it is compatible with Ubuntu version or i will need to reparted it.

Now i have a dual version with android and ubuntu (https://forum.meizufans.eu/topic/4770/tutorial-dual-booting-cyanogenmod-and-ubuntu-touch-on-android-version-mx4)  and i want to delete androir version but i dont know how to do it.

Thanks

**Comment by MariusQuabeck** [comment]
Hi,

please see http://forum.xda-developers.com/meizu-mx/general/meizu-mx4-how-to-flash-ubuntu-touch-t3210039
