### ISSUE TITLE
this is good job , can you adapt to meatal Meizu for me ?  

### ISSUE THREAD

**Issue by icedifferent** [MariusQuabeck/magic-device-tool#30]
I am a Chinese and is a novice programmer and i am very interesting in ubuntu,so i very hope you can adapta it to meizu metal,
this is the product url :http://www.meizu.com/products/meilanmetal/summary.html

**Comment by Happywormwood** [comment]
魅族不是本省就支持ubuntu么

**Comment by icedifferent** [comment]
不是啊，只有mx4 和MX5pro才支持

**Comment by Happywormwood** [comment]
sorry,看错了


在 2016/10/25 16:23, icedifferent 写道:

**Comment by ahoneybun** [comment]
Hey @icedifferent this tool is for installing currently supported devices, you might want to look at the ubports project: https://ubports.com/ for adding new unofficial devices such as yours.
