### ISSUE TITLE
Check for "add-apt-repository" and install if needed?

### ISSUE THREAD

**Issue by pdsouza** [MariusQuabeck/magic-device-tool#35]
Thanks for your work, this is a pretty cool tool! I had one issue I ran into while trying it out though.

I don't have "add-apt-repository" installed on my system (docker image ubuntu:16.04) and the script skips installing needed packages like adb/fastboot and proceeds to device selection without reporting an error until it tries to use adb/fastboot.

I had to manually install this package (contains "add-apt-repository") to get the script dependencies to install as expected:

```
$ sudo apt-get install software-properties-common
```

Maybe you can check if this exists on the system and install it if needed?

P.S. I work on Maru OS, so thanks for supporting our project with your tool!

**Comment by MariusQuabeck** [comment]
Hey, thanks for reporting this! I haven't even thought about systems that don't have the `apt-add-repository` tools preinstalled. I will fix this soon!
Keep up the good work!

**Comment by MariusQuabeck** [comment]
Fixed by @Flohack74 https://github.com/MariusQuabeck/magic-device-tool/commit/680f9a23e780024f2c95895628e0bc4563924318

Thanks :)

**Comment by Flohack74** [comment]
Just to note, the current fix is Ubuntu-version-specific, as this package has been renamed. So it wont work before Ubuntu 14.xx or so :)

**Comment by MariusQuabeck** [comment]
thats fine :)

> System Requirements
> ----
> - Ubuntu 16.04 and above
> - A device from the supported list below
> - USB cable for your device
> - Internet connection
