### ISSUE TITLE
Logo as SVG so it looks better

### ISSUE THREAD

**Issue by tsimonq2** [MariusQuabeck/magic-device-tool#36]
Do you guys have an SVG image you can provide in this directory that you can use instead of PNG? It looks MUCH better as it exports as shapes rather than pixels.

**Comment by michaelkisiel** [comment]
The svg's should now be centralized. Have a look at the [repo](https://github.com/michaelkisiel/mdt-icons) @MariusQuabeck

**Comment by michaelkisiel** [comment]
+1

**Comment by MariusQuabeck** [comment]
We will keep the .png . thanks everyone
![bildschirmfoto vom 2016-10-31 17-57-32](https://cloud.githubusercontent.com/assets/17063564/19863223/a82d19b4-9f93-11e6-9726-e1293f97c025.png)
