### ISSUE TITLE
IMEI number

### ISSUE THREAD

**Issue by konnnGit** [MariusQuabeck/magic-device-tool#37]
Hello, is there any way put the IMEI number to the certain point via developer mode (Ubuntu touch Aquaris E5 HD) ? These number are missing and the sim cards network considered unregistered.

**Comment by MariusQuabeck** [comment]
The tool can not be responsible for removing the IMEI partitions! No, you have to send it back to BQ for repair.

**Comment by konnnGit** [comment]
Well, I have no any hint against the tool. 

Respectively to android engineer mode (when key the *#*#13646633#*#* code) where anyone is able to set the IMEIs is there any such a way?

**Comment by MariusQuabeck** [comment]
**Why are you opening an issue here then ?** 

In android, you can set the IMEIs manually but that won't help you in ubuntu. the partitions are still missing and your network manager will act weird on wifi.

**Comment by konnnGit** [comment]
Certainly the issue is an "issue" and here there is a deep knowledge. I try to match the android IMEIs manually set to an ubuntu one. Such an issue is eliminated when flashing to android and appeared only in the opposite direction.

**Comment by MariusQuabeck** [comment]
I'm closing this now. You can get help on #ubuntu-touch on irc.freenode.net but not here where it doesn't belong to

**Comment by konnnGit** [comment]
Thank you.
