### ISSUE TITLE
< waiting for device >

### ISSUE THREAD

**Issue by Dav4321** [MariusQuabeck/magic-device-tool#38]
thanks for this tool!

im trying to install Ubuntu on my OnePlus One. my device is in fastboot mode and your script detects it. my terminal reads:

```
Flashing stable channel

< waiting for device >
```

How long is this step supposed to take?

**Comment by MariusQuabeck** [comment]
Hi,

I've just verified that it works. Please try a different usb cable.
not kidding, you can't imagine how often the cable is the issue even if it's detectable by fastboot.

Another known issue is that the OnePlus One locks up while trying to reboot into the recovery. There isn't much I could do about that but it usually works on the second or third try with the tool.

Feel free to join the magic-device-tool chat on telegram for further support or questions.

![photo_2016-11-08_14-27-42](https://cloud.githubusercontent.com/assets/17063564/20100845/8861341c-a5bf-11e6-805d-5445a0b2772e.jpg)
