### ISSUE TITLE
Flashing Mx4 on LinuxMint

### ISSUE THREAD

**Issue by alexisaeff** [MariusQuabeck/magic-device-tool#39]
Flashing stable channel

FAILED (remote: not support on security)
FAILED (remote: not support on security)
rebooting into bootloader...
FAILED (remote: not support on security)
finished. total time: 0.020s

recovery-arale.img  100%[===================>]  13,38M  3,59MB/s    in 4,0s    
sending 'recovery' (13704 KB)...
OKAY [  0.696s]
writing 'recovery'...
FAILED (remote: 
Security deny - Err:0x2017 
)
finished. total time: 0.762s
2016/11/04 01:27:17 Device is |arale|
2016/11/04 01:27:17 Flashing version 15 from ubuntu-touch/stable/meizu.en channel and server https://system-image.ubuntu.com to device arale
2016/11/04 01:27:17 mkdir /root/.cache: permission denied

Move to your device to finish the setup.

Cleaning up..

Exiting script. Bye Bye

**Comment by MariusQuabeck** [comment]
1.
`FAILED (remote: not support on security)
FAILED (remote: not support on security)
rebooting into bootloader...
FAILED (remote: not support on security)`
and
`writing 'recovery'...
FAILED (remote:
Security deny - Err:0x2017
)`
shows that the bootloader of your MX4 is locked. see http://forum.xda-developers.com/meizu-mx/general/meizu-mx4-how-to-flash-ubuntu-touch-t3210039 for how to change this.

2. You are using it on Linux Mint which is not officially supported by the tool (even if there is a shared ubuntu codebase, some things are different)
Please see the Requirements section in the README

**Comment by alexisaeff** [comment]
Thank you. Realy device is locked and need signed firmware for unlock.

**Comment by MariusQuabeck** [comment]
@alexisaeff Check out the sp flash tool from the xda link. It unlocks the bootloader and you can flash ubuntu on it

**Comment by alexisaeff** [comment]
Ok.Thank you:)

2016-11-11 18:14 GMT+03:00 Marius Quabeck <notifications@github.com>:
