### ISSUE TITLE
Meizu MX4

### ISSUE THREAD

**Issue by extraymond** [MariusQuabeck/magic-device-tool#42]
Can't install ubuntu touch on android version of mx4.
Even after unlocking the bootloader with custom recovery.

The error message is 
[FAILED (remote: not support on security)]

**Comment by MariusQuabeck** [comment]
> [FAILED (remote: not support on security)]

shows that the bootloader of your MX4 is still locked. see http://forum.xda-developers.com/meizu-mx/general/meizu-mx4-how-to-flash-ubuntu-touch-t3210039 for how flash ubuntu on a non ubuntu edition mx4
