### ISSUE TITLE
Samsung S5 g900h

### ISSUE THREAD

**Issue by nexcax** [MariusQuabeck/magic-device-tool#43]
Add support for this device please.

Nice work

**Comment by tim-sueberkrueb** [comment]
hi

**Comment by kristbaum** [comment]
Standard Answer:
mdt will not be made for devices that don't support tools like adb + fastboot. Heimdall is to unstable for production use, feel free to fork, and try it, it's really bad. 
So in short: No Samsung devices for now!

**Comment by MariusQuabeck** [comment]
Standart Answer 2:
mdt will not support any phones or tablets without already ported ubuntu for them. Feel free to port and maintain it yourself, spin up an image server, maintain regularly ota updates and come back here and ask again.
