### ISSUE TITLE
No space left on device.

### ISSUE THREAD

**Issue by m1r4g3** [MariusQuabeck/magic-device-tool#48]
I'm trying install Ubuntu on BQ Aquaris M10 FHD. It works normally until I hit the below error, then it stops. It seems to push 5 files to the device. The first 4 files are successful. This error is for the 5th one. The device is in recovery mode when it happens, and if I reboot, it reboots back into Android instead of Ubuntu. I followed all instructions. Android is set to developer mode with USB debugging. Am I missing something?

2016/12/25 13:57:32 error pushing: failed to copy '/home/user/.cache/ubuntuimages/pool/ubuntu-312c862adc434562d47089b8a6c9991f6774e6665cf4b303afbce77724d5cd75.tar.xz' to '/cache/recovery//ubuntu-312c862adc434562d47089b8a6c9991f6774e6665cf4b303afbce77724d5cd75.tar.xz': No space left on device

**Comment by MariusQuabeck** [comment]
If you're comming from android you have to use the SP flash tool. more info & instructions: http://askubuntu.com/questions/761070/cant-install-ubuntu-touch-on-bq-aquaris-m10
