### ISSUE TITLE
Snap version: ubuntu-device-flash not found...

### ISSUE THREAD

**Issue by fadeouter** [MariusQuabeck/magic-device-tool#52]
...when I trying to install Ubuntu to OPO. Of course, all dependencies installed on my system (Ubuntu 16.10 32-bit). 
Script from git works well.

**Comment by dtmonterrey** [comment]
Off Topic: how is your experience with the OPO? I have one but only once I was able to install using devel_rc-proposed channel.

**Comment by MariusQuabeck** [comment]
@fadeouter Thanks for reporting, we'll look into this. For OPO please use the script version and make sure to start it with
sudo ./launcher.sh

@dtmonterrey feel free to join our telegram group chat

**Comment by fadeouter** [comment]
@dtmonterrey, same, devel_stable channel also not work. Very sad!
@MariusQuabeck, ok, thanks. Maybe add a note about 'sudo' to a README?

**Comment by MariusQuabeck** [comment]
@fadeouter its already part of the dialog and only needed for OPO and FP2.
Also devel_rc-proposed _is_ working. You have to reboot it a few times until unity comes up. Also please wait 10 minutes after mdt says its done and then reboot manually.

**Comment by MariusQuabeck** [comment]
**Note for mdt team:**
The sudo problem for OPO and FP2 should be fixed when we switch back to snap classic confinement.

**Comment by dtmonterrey** [comment]
@MariusQuabeck you are awesome... I'm already in the Telegram group for FP2, but my current life doesn't allow me to get more into UT. I envy my sister that has a BQ Aquaris 5 UT, and I can't have it on my OPO :(

One tip for improvement: show a message saying to wait at least 10min after the script finishes.

**Comment by MariusQuabeck** [comment]
@dtmonterrey thanks I will add the message with the next update

**Comment by MariusQuabeck** [comment]
Added to TODO 
https://github.com/MariusQuabeck/magic-device-tool/commit/004f5b40757599dfe3ea763244c825f54f8eef45
