### ISSUE TITLE
Bad Interpreter

### ISSUE THREAD

**Issue by Mangnoppa** [MariusQuabeck/magic-device-tool#53]
Hi Marius,

very nice tool. I just cloned your repository and when I launch `launcher.sh` I get the following error message:

    bash: ./launcher.sh: /bin/bash^M: Bad Interpreter: file or directory not found

That's because of the CRLF you use in the file. You can see this when you try to start the script with: 

    $ bash ./launcher.sh 
    ./launcher.sh: Zeile 2: $'clear\r': Kommando nicht gefunden.
    ./launcher.sh: Zeile 3: Syntaxfehler beim unerwarteten Wort `$'\r''
    '/launcher.sh: Zeile 3: `exists()

I have a german installation, but I think that points it out.
A simple `dos2unix ./launcher.sh` solved the problem for me.

Greeting Mangnoppa

EDIT: Just checked: That problem is, of course, not only limited to `launcher.sh`. It affects all shell-scripts.

**Comment by MariusQuabeck** [comment]
Hi @Mangnoppa,

thanks for reporting this. I'm confused.. does your system meet the requirements?

> System Requirements
> ----
> - Ubuntu 16.04 and above
> - A device from the supported list below
> - USB cable for your device
> - Internet connection

The errors don't really look like Ubuntu 16.04/16.10, gnome-terminal/xterm

**Comment by Mangnoppa** [comment]
Hi @MariusQuabeck,

I have a Linux Mint 18 installation and I use Terminator as a terminal emulator but even with gnome-terminal it's not working. I can test it tomorrow on Ubuntu 16.04

I own a bq E4.5, it was not attached to the pc but I see no reason for that. The script is not even starting, because there is a `\r\n` at the end of `#!/bin/bash`. I just cloned your repository and executed `./launcher.sh`

Mangnoppa

**Comment by MariusQuabeck** [comment]
As your system doesn't meet the requirements and it's proven to work fine on Ubuntu I'll close this.
Feel free to join our telegram group for further support
