### ISSUE TITLE
Winblows 10 version~Feb '17

### ISSUE THREAD

**Issue by annaleaser** [MariusQuabeck/magic-device-tool#54]
public bug.

needs a windows 10 version for easy instal
 do you need bounties (?) for this; if so look at
https://github.com/bhdouglass/uappexplorer

and see how he has given a jugdement on each bug, of the compexity ;-)

**Comment by MariusQuabeck** [comment]
MDT is relying on _ubuntu-device-flash_ and I'm not interested in re-engineering that so until snaps work on windows the answer is no.

**Comment by annaleaser** [comment]
what about the complexity tags ?

**Comment by MariusQuabeck** [comment]
We will discuss this if we think this is useful or not. So far there was no need for that.
