### ISSUE TITLE
Nexus 7 (flo): Staging channel not availble

### ISSUE THREAD

**Issue by haecker-felix** [MariusQuabeck/magic-device-tool#55]
Why there is no staging channel for the nexus 7 2013 (flo)?

with the mdt there are only following channels available:
"[1] stable"
"[2] rc-proposed"

But:
**ubuntu-device-flash query --list-channels --device=flo**
```
ubuntu-touch/devel/krillin.en
>> ubuntu-touch/staging/ubuntu <<
ubuntu-touch/rc/ubuntu
ubuntu-touch/devel/ubuntu
ubuntu-touch/stable/ubuntu
ubuntu-touch/rc-proposed/ubuntu
ubuntu-touch/rc-proposed/ubuntu-pd
ubuntu-touch/rc/ubuntu-pd

```
___________________________________________
There are images available:
http://system-image.ubuntu.com/ubuntu-touch/staging/ubuntu/flo/

`sudo ubuntu-device-flash touch --channel ubuntu-touch/staging/ubuntu --device flo --bootstrap`
-> Successfull flash, but it hangs at the google logo.

Maybe you can help me. I want to try the staging channel (/ ubuntu 16.04 with the _latest_ unity8).
Thanks.

**Comment by MariusQuabeck** [comment]
Hello @haecker-felix,

yes there are images available in the staging channel for all devices but the only devices that these images get maintained for atm are the m10 hd (cooler) and m10 fhd (frieza).
For all other devices the images are supposed to not boot so there is no reason to add the staging channel to MDT for devices where it doesn't work.

I will add the staging channel if this changes :)
