### ISSUE TITLE
Android on vegetahd

### ISSUE THREAD

**Issue by fneddy** [MariusQuabeck/magic-device-tool#59]
There is an official android version for the vgetahd. Could you ad an option to install it?

**Comment by MariusQuabeck** [comment]
Hey @fneddy ,

unfortunately the bootloader on BQ devices is locked down and BQ doesn't distribute their OTA images as zips so you have to use their own OEM tool or the SP Flash tool. MDT is currently not able to flash them.
You can find instructions for how to do this here:
https://www.youtube.com/watch?v=U9OQovPAbw4

Best regards
Marius
