### ISSUE TITLE
No MD5 checking

### ISSUE THREAD

**Issue by mabkenar** [MariusQuabeck/magic-device-tool#61]
First, thank you for this really awesome tool. Very very very well done :)

Now to the issue: I just installed LineageOS (without GApps) on my Nexus 4). Everything went fine. But I noticed this in the terminal:

```
Installing LineageOS..
Installing zip file '/sdcard/lineage-14.1-20170125-nightly-mako-signed.zip'
Checking for MD5 file...
Skipping MD5 check: no MD5 file found
Target: google/occam/mako:5.1.1/LMY48M/2167285:user/release-keys
```

Is this lack of MD5 checksum expected? I would like my OS image be checked against corrupt downloads.

**Comment by MariusQuabeck** [comment]
Hi @mabkenar thanks for reporting this. The missing checksum function happens to be missing inside of the LineageOS installer and is not part of MDT so I'm closing this.

**Comment by mabkenar** [comment]
Thanks for the swift response. So could you please guide me where should I go to fix this problem?

**Comment by MariusQuabeck** [comment]
@mabkenar I'll try to find out and will get back to you soon
