### ISSUE TITLE
Slightly outdated LineageOS image at the time of install

### ISSUE THREAD

**Issue by mabkenar** [MariusQuabeck/magic-device-tool#62]
I just installed LineageOS for my Nexus 4 today (February 20th 2017), and immediately booted into it. The installed image is **14.1-20170125-NIGHTLY-mako**, i.e. from January 25th.

But when I check for LineageOS updates, I see that there are already [three more recent images](https://download.lineageos.org/mako) released for Nexus 4. 

Is this expected that the installer is slightly behind LineageOS releases? I remember that Cyanogenmod provided a **NIGHTLY-latest** image, which always linked to the very latest nightly build. Could you somehow do the same?

Thank you very much!

**Comment by MariusQuabeck** [comment]
Yes the LineageOS version that mdt ships is slightly behind because there is no nightly-latest image I could link to yet. It's on my list and as soon as things change over at Lineage I'll fix this. Until then I will update the download link periodically

**Comment by MariusQuabeck** [comment]
I've updated all links again, there is no better solution for this for now
