### ISSUE TITLE
BQ Aquaris E5 HD, Ubuntu Edition speakers not working

### ISSUE THREAD

**Issue by coko69** [MariusQuabeck/magic-device-tool#63]
My phone does not ring / play sound on speakers. No problems to answer calls, when having notice by vibrating / display notification; Have phone for some weeks now - at very beginning it worked; short after it stopped playing sounds; swithched sound on in pathwind & uninstalled pathwind - no difference; sometimes it plays ringtones - but have no idea under which circumstances; even when it rang for one time it does not anymore one call later, although I did not make any changes in settings between the calls; does not play sounds / ringtones when selecting them in settings (no difference which ringtone).

I reinstalled the system, I stopped the game PathWind sound and I uninstalled and after I installed without any effect, I reinstalled it PulseAudio but without effect.
Thank you for an answer or suggestion.

**Comment by MariusQuabeck** [comment]
Hello @coko69,

this is not related to **magic-device-tool** so I'm closing this.
Please report this bug here: https://bugs.launchpad.net/canonical-devices-system-image/+filebug
