### ISSUE TITLE
BQ aquaris M10 FHD ubuntu

### ISSUE THREAD

**Issue by leodumont** [MariusQuabeck/magic-device-tool#64]
Hi,
Thanks for your work.
Quick question about device compatibility : does magic-device-tool work with the ubuntu edition of the Aquaris M10 FHD from BQ ? Is-it for example possible to install Android or better Lineage OS on it (but for this last one, I'm note sure a ROM is available) ?
Thks in advance,

**Comment by MariusQuabeck** [comment]
Hi @leodumont,

yes the BQ Aquaris M10 FHD codename frieza/freezerfhd that got sold as "Ubuntu Edition" is supported.

> 
> Supported devices
> ----
> 
> - ...
> - BQ Aquaris M10 FHD (frieza)
> - ...

It is possible to install android on it but not through magic-device-tool as the BQ stock android is using the mtk image format for which you have to use the SP flash tool. You can find more info on how to do this [here](http://www.mibqyyo.com/comunidad/discussion/75471/is-there-any-guidance-i-can-replace-the-ubuntu-with-android-for-m10-fhd/). 

There is no LineageOS port available for it yet and probably never will be.
