### ISSUE TITLE
Problems during install maruOS on N7 from LubuntuOS

### ISSUE THREAD

**Issue by Bmme2GFTbU** [MariusQuabeck/magic-device-tool#68]
Background:

- Acer One Netbook
- Lubuntu 16.10
- Kernel 4.8.0-41

Procedure:

1.) I'm trying to install mdt with `sudo snap install magic-device-tool`. It worked. 

2.) After installing mdt I started mdt (`magic-device-tool`) to install maruOS on flo (Nexus 7 2013 Wifi).

3.) No device was recognized. (adb and fastboot was not installed before) After installing adb (`sudo apt install adb`) and fastboot (`sudo apt install fastboot`). Fastboot recognized device in fastboot-mode with `sudo fastboot devices`. Mdt never detect device, even after installing adb and fastboot manually.

4.) Using mdt-script-version after cloning git repository (`sudo ./install.sh`). Adb and fastboot were installed during startup-process (even after installing adb and fastboot manually). Flashing maruOS on flo worked with mdt-script-version.

5.) After starting mdt-script-version again, adb and fastboot were installed again. 

Device could be borrowed to reproduce error. Contact Alex on Telegram for further information or lending device.

**Comment by MariusQuabeck** [comment]
Hey thanks for reporting this !
I'm afraid I have to close this as invalid. You haven't followed the instructions completely..

> Usage
> -----
> 
> Advanced:
> 
> ```
> sudo snap install magic-device-tool **--devmode**
> ```
> Run the snap
> ```
> magic-device-tool
> ```
