### ISSUE TITLE
krillin to android

### ISSUE THREAD

**Issue by JonnyTech** [MariusQuabeck/magic-device-tool#70]
Now that Ubuntu have announced that they have dropped Touch, I want to make my Aquaris E4.5 (krillin) an Android device. Is this implemented in magic-device-tool? Issue #21 mentions finding a ROM but I cannot find any recovery or ROM for this device online.

**Comment by dentaku65** [comment]
I was able to install Android on E4.5 via https://itsfoss.com/install-android-ubuntu-phone/ but even if I installed TWRP recovery I'm unable to load krillin ROMS (cyanogenmod 12.1 and 13); is the hardware different from the E4.5 Android version? Is there any chances to have cyanogen/lineageos on the Ubuntu Touch E4.5?

thx

**Comment by MariusQuabeck** [comment]
the hardware is identical, you have to use the oem tool as described in Issue #21 and not twrp

**Comment by dentaku65** [comment]
ok I did with stock image. My question was that on Ubuntu Phone E4.5 Cyanogenmod port do not work at all the moment; I was asking if in the future will be. Sorry if I explained incorrectly

**Comment by MariusQuabeck** [comment]
@dentaku65 I'm the maintainer of **magic-device-tool** and not the maintainer of the CyanogenMod port so you shouldn't ask me.
