### ISSUE TITLE
OPO Lineage does not work

### ISSUE THREAD

**Issue by stekalb** [MariusQuabeck/magic-device-tool#73]
Whenever I try to flash lineage os, it fails. MDT does not copy the img to the device. Tested with snap version as well with script version
![photo_2017-04-26_14-45-58](https://cloud.githubusercontent.com/assets/28052594/25435109/4742bef6-2a8f-11e7-8a0d-e748918b4cd7.jpg)

**Comment by MariusQuabeck** [comment]
please make sure that you've started the launcher.sh as root. Otherwise it can't see the fastboot & adb interface.

I can test this in a few days but I don't think mdt is the problem here

**Comment by stekalb** [comment]
I started it with sudo. Flashing Ubuntu worked, but lineage failed.

**Comment by stekalb** [comment]
After I successfully flashed ubuntu, flashing lineage worked.
