### ISSUE TITLE
OPO installing the Openstore does not work

### ISSUE THREAD

**Issue by stekalb** [MariusQuabeck/magic-device-tool#74]
When I try to install the Openstore MDT claims that the device is not found (dev mode is enabled, device unlocked, channel devel_rc-proposed)

**Comment by stekalb** [comment]
ADB does not work on r267. Filed bug on launchpad: [https://bugs.launchpad.net/ubports-opo/+bug/1686467](url)

**Comment by MariusQuabeck** [comment]
@stekalb also ping @mariogrip to fix the adb/phablet-shell interface. on all ports from UBports phablet-shell connects as root instead of phablet so mdt can not work like this since there is no ~/Downloads folder for root
