### ISSUE TITLE
775MB of Local Storage after Cyanogenmod installation on Meizu MX4 16GB Ubuntu Edition

### ISSUE THREAD

**Issue by ahelmel** [MariusQuabeck/magic-device-tool#75]
After the installation of Cyanogenmod on a Meizu MX4 16GB Ubuntu Edition only 775MB of local storage are usable/recognizable:

![cyanogenmod-on-meizu-mx4-16gb-ubuntu-edition__modified](https://cloud.githubusercontent.com/assets/756820/25780610/49dba01c-332a-11e7-862d-3ff4c3018251.jpg)

**Comment by MariusQuabeck** [comment]
Hello @ahelmel,

this is a known issue if you're coming from ubuntu because the partitioning is differently there.
There is no convinient or automatable way to fix it but I'll do my best to integrate it in mdt soon.

Thanks for reporting this!
Marius

**Comment by ahelmel** [comment]
Ok, thanks for the answer. I installed FlymeOS, Version 6.7.3.3G beta instead of Cyanogenmod. Now i have the full 16GB of local storage.

**Comment by NodokaMurmevent** [comment]
you can correct the problem if you wipe all data with TWRP recovery, i have do this and storage place are come back, obviously it's wipe all data :) 

1) install cyanogenmod
2) start TWRP recovery and wipe all data
3) normal boot you phone and let cyanogenmod create all he need
4) ???
5) PROFIT

**Comment by MariusQuabeck** [comment]
This does not solve the problem of the ubuntu edition having a different partition layout. MDT already reformats the partitions. You can fix this by flashing the ubuntu kernel zip, let it bootloop and then reflash the cm kernel. this recreates the partition tables. Sadly this is not automatable in mdt as it involves manual reboots

**Comment by MariusQuabeck** [comment]
@ahelmel please try the "Fix local storage issue" from the MX4 menu :) https://github.com/MariusQuabeck/magic-device-tool/commit/80c33717e80a30acdbf3852e011fb25587778a08
