### ISSUE TITLE
Nexus 7 2012 (grouper)

### ISSUE THREAD

**Issue by justinkelly** [MariusQuabeck/magic-device-tool#78]
Any chance that the Nexus 7 2012 (grouper) would be added to the list of supported devices?

**Comment by MariusQuabeck** [comment]
Hey @justinkelly,

please see the [FAQ](https://github.com/MariusQuabeck/magic-device-tool#faq) section:

> FAQ
> ---
> - Q: Will you support "device x"?     
>   A: You can open an issue for a new device, if it has a working port of Ubuntu Touch. Most of them are at [ubports.com](https://ubports.com/). If your device isn't there, it probably has no working port, so please don't open new issues.

There is no Ubuntu Port for the Nexus 7 2012, therefore we will not add it.

Actually, there is a armhf7 port of Ubuntu Desktop 13.10 for it. Maybe I'll add that one after we've switched to the GUI version.

**Comment by justinkelly** [comment]
thanks @MariusQuabeck !
