### ISSUE TITLE
Lineage OS Setup Wizard Crashes on Nexus 5

### ISSUE THREAD

**Issue by JWBrittain** [MariusQuabeck/magic-device-tool#85]
Setup Wizard crashed repeatedly in Lineage OS, and I could not get  my Nexus 5 set up. 

This seems to be caused by the version of gapps used.  I bumped the version in the script to the newest version (open_gapps-arm-7.1-nano-20170603.zip) and everything worked, but I don't know if there are ramifications I'm not aware of.

Thanks for all your work on this!
James.

**Comment by MariusQuabeck** [comment]
Hey James,

thanks for reporting this. It's already fixed https://github.com/MariusQuabeck/magic-device-tool/commit/24485bb50d7f60e8dae900ef18fc71c5b92a92a7

**Comment by MariusQuabeck** [comment]
Hey James,

thanks for reporting this. There seems to be a problem with the recent gapps zips. I've fixed something similar earlier today https://github.com/MariusQuabeck/magic-device-tool/commit/24485bb50d7f60e8dae900ef18fc71c5b92a92a7 .

I will do the same for the Nexus 5 now.

Best regards
Marius

**Comment by MariusQuabeck** [comment]
fixed with https://github.com/MariusQuabeck/magic-device-tool/commit/98c1f1c45f43f56c56c1619ef998e909a4683bb2
