### ISSUE TITLE
Update Maru to latest release 0.4.1

### ISSUE THREAD

**Issue by pdsouza** [MariusQuabeck/magic-device-tool#88]
Just a heads-up that 0.4.1 was recently released for Maru OS, downloads can be found here: https://github.com/maruos/maruos/releases/tag/v0.4.1.

Thank you for the great work @MariusQuabeck !

**Comment by MariusQuabeck** [comment]
hey @pdsouza,

thanks for the heads-up!
I'm at a conference rn, I'll try to update it asap

**Comment by pdsouza** [comment]
Wow, that was fast! Thanks again :)
