### ISSUE TITLE
Setup does not finish on OPO

### ISSUE THREAD

**Issue by piscopoc** [MariusQuabeck/magic-device-tool#94]
Having some trouble completing the UBPorts installation, it is able to flash verion 44 to the device but does not complete when the device reboots into recovery. Below is the message I get:
---
Waiting for device to enter recovery mode ...
Failed to enter Recovery

Move to your device to finish the setup.

Cleaning up..

Exiting script. Bye Bye
---

Currently running the process on Ubuntu 17.04. Any thoughts on why this would be happening?

**Comment by KristijanZic** [comment]
Os: Ubuntu 17.04
Device: hammerhead

I had a similar problem earlier today.

Without really looking at the script I can see my device trying to boot before the rom zip is even pushed to the device let alone installed. It should instead go to the recovery mode and then try to adb push.
Also mdt requires sudo because fastboot requires it.

```
Installing TWRP recovery

target reported max download size of 1073741824 bytes
sending 'recovery' (14626 KB)...
OKAY [  0.685s]
writing 'recovery'...
OKAY [  1.125s]
finished. total time: 1.809s

Rebooting device..

This will take ~35 seconds. Don't disconnect your device!

rebooting into bootloader...
OKAY [  0.000s]
finished. total time: 0.050s
downloading 'boot.img'...
OKAY [  0.591s]
booting...
OKAY [  0.117s]
finished. total time: 0.708s
error: device not found

Pushing zip's to device

Please wait this can take a while

You may see a prompt asking you for read/write permissions
Ignore that prompt, the tool will take care of the installation

  → LineageOS 14.1 zip 
error: device not found

  → gapps zip
error: device not found

=========================================

Installing LineageOS 14.1..

error: device not found

Installing Open GApps..

error: device not found

Wipe cache..

error: device not found
error: device not found

error: device not found
The device is now rebooting. Give it time to flash the new ROM. It will boot on its own.


Cleaning up..

Exiting script. Bye Bye

```

**Comment by MariusQuabeck** [comment]
@piscopoc Please try again with a different USB cable and port, I've tried to verify your issue but it works fine here and for others.

@KristijanZic please open a separate issue for this also I was not able to verify your issue either and MDT is already doing what you've suggested.
