### ISSUE TITLE
UBports backup-script needs developer-mode

### ISSUE THREAD

**Issue by NeoTheThird** [MariusQuabeck/magic-device-tool#96]
Developer-mode needs to be enabled on the device in order for the backup script to work.

**Comment by tenleftfingers** [comment]
If the screen needs to remain unlocked for the backup proceedure to complete successfully, please add that too (I'm still testing to see if this is the case).

**Comment by MariusQuabeck** [comment]
@Flohack74 ^

**Comment by Flohack74** [comment]
@tenleftfingers The screen does not need to stay unlocked, but you need to enable developer mode and authenticate the PC. I put there a message if there is no connection possible to the device:
![grafik](https://user-images.githubusercontent.com/16186470/28532020-cb5bd6c4-7098-11e7-8d39-83d16ae1dc43.png)

**Comment by Flohack74** [comment]
I also added some code to not copy symbolic links anymore.

**Comment by MariusQuabeck** [comment]
I've merged your pull request @Flohack74 can I close this?

**Comment by Flohack74** [comment]
I think so, I did a test and wfm, but maybe we find an indepemndent tester? :)

**Comment by MariusQuabeck** [comment]
@NeoTheThird ^ ? 😇

**Comment by NeoTheThird** [comment]
Looks good. Only complaint would be that there's more whitespace in front of "Back up your UBports device".
