### ISSUE TITLE
Install UBPorts from a Fedora machine to a BQ M10FHD?

### ISSUE THREAD

**Issue by mckea** [MariusQuabeck/magic-device-tool#99]
I have a BQ M10FHD and would like to install UBPorts on it - but I don't use Ubuntu on my workstations.

Is it possible to install from Fedora?

**Comment by MariusQuabeck** [comment]
Hello @mckea,

snapd is supported on Fedora afaik so you can use the snap version of MDT.
https://snapcraft.io/docs/core/install-fedora
`sudo snap install magic-device-tool --devmode`

If your device is still/already running Ubuntu please ignore the following and just continue with installing Ubuntu via MDT:

The BQ Android ROM locks the bootloader and has a different partition layout so you have to change this first to flash Ubuntu on your device.
First download the SP Flash Tool: https://spflashtool.com/
Download the "old/canonical" Ubuntu image: http://mdt-files.com/downloads/old/m10fhd.zip

Use SP Flash Tool to install the image on your device.
**Make sure to select Firmware Upgrade, every other option will damage your device**
![photo_2017-07-24_17-05-44](https://user-images.githubusercontent.com/17063564/28529964-6fe9aa42-7092-11e7-895e-d2d24426f598.jpg)

After installing Canonicals Ubuntu on your device, don't even bother setting it up, you just did this to unlock the bootloader.
Now you can use MDT to flash UBports Ubuntu.

Feel free to join our Telegram Chat if you need any assistance :)
http://magicdevicetool.com/telegram
